### ISSUE TITLE
Use AddVoidReturnTypeWhereNoReturnRector on classes extending TestCase

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-phpunit#113]
There exists a rector rule called `AddVoidReturnTypeWhereNoReturnRector`. It would be nice if we could add to `rector-phpunit` to the `PHPUNIT_CODE_QUALITY` a rule to add this to all classes extending from PHPUnits `TestCase` class or any other class extending from PHPUnit TestClass. The `AddVoidReturnTypeWhereNoReturnRector` is currently final.

What do you think the best way is to implement this. Currently we can not extend from `AddVoidReturnTypeWhereNoReturnRector` to achieve this simple here. Another option could be that we extend the `AddVoidReturnTypeWhereNoReturnRector` Rule in rector itself to filter by a class / interface and apply the rule only for that kind of classes, not sure if that kind of things make sense as a "General" Rector feature. That all rules could be limited to specific classes extending or implementing from a specific interface?

**Comment by TomasVotruba** [comment]
Hi, I like the idea, yet it would creep the features across various sets and projects. 
This is similar answer as in other issue - the sets should be as unique and idempotent as possible.

In the end the most project will use combination of sets from core + couple from vendor packages.

**Comment by alexander-schranz** [comment]
@TomasVotruba I understand, maybe then the best way in this situation is creating different `rector` config files for different directories so an own `rector.php` file for the `tests` directory.

**Comment by TomasVotruba** [comment]
That would lead to false positives, as PHPStan and Rector need to understand the whole project: 
https://phpstan.org/blog/why-you-should-always-analyse-whole-project

**Comment by alexander-schranz** [comment]
In my case the hard part is that I can add `AddVoidReturnTypeWhereNoReturnRector` only to files which are not part of `backwards compatibility promise` :). For normal projects I completely agree to keep equal over the whole project.
