### ISSUE TITLE
AssertEqualsToSameRector converts even if testing arrays contain objects

### ISSUE THREAD

**Issue by vitxd** [rectorphp/rector-phpunit#118]
Given the following code:
```php
$expected = ['date' => new DateTimeImmutable('2022-10-31 12:32:33')];
$date = new DateTimeImmutable('2022-10-31 12:32:33');
$actual = compact('date');

self::assertEquals($expected, $actual);
```

The new version of the rule will change the assertion to `assertSame` but this would lead to an error given this will check the two arrays contain exactly the same object.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,that way we can reproduce the bug.

**Comment by vitxd** [comment]
Ok, I cannot replicate my issue on that demo but I can by upgrading rector to the latest version... is it that rector is not loading the latest version of this library?

**Comment by TomasVotruba** [comment]
Thanks for the demo link! It looks legit bug :+1: 

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.

**Comment by vitxd** [comment]
done! https://github.com/rectorphp/rector-phpunit/pull/119

That feature is cool btw! 😄

**Comment by vitxd** [comment]
Hello, I don't think it's fixed 😓 
https://github.com/rectorphp/rector-phpunit/pull/121

It only works on the first level of an array and not taking care if the object might be on a second/third/whatever level
