### ISSUE TITLE
PHP Fatal error in Rector 0.11 when import PHPUnitSetList::PHPUNIT_CODE_QUALITY

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector-phpunit#13]
```
PHP Fatal error:  Uncaught Error: Class "RectorPrefix20210513\Nette\Loaders\RobotLoader" not found in /home/runner/work/coding-standard/coding-standard/vendor/rector/rector/vendor/rector/rector-phpunit/src/RobotLoader/RobotLoaderFactory.php:14
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
How can we reproduce?

**Comment by zingimmick** [comment]
demo.php
```php

**Comment by zingimmick** [comment]
1. `composer require rector/rector phpunit/phpunit`
2. Create `demo.php`
```php
<?php

class SomeService
{
}

use PHPUnit\Framework\TestCase;

class SomeServiceTest extends TestCase
{
}
```
3. Create `rector.php`
```php
<?php

declare(strict_types=1);

use Rector\PHPUnit\Rector\Class_\AddSeeTestAnnotationRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(AddSeeTestAnnotationRector::class);
};
```
4. Run `vendor/bin/rector process demo.php -vvv`

**Comment by TomasVotruba** [comment]
Hi, thanks. I could reproduce it!

This is actually one of rules we forgot to remove while moving to static reflection.
This rule uses manual loading of classes in assumed paths in your project. It also uses dynamic reflection. In Rector 0.9 we switched to static reflection: https://getrector.org/blog/2021/03/15/legacy-refactoring-made-easy-with-static-reflection

Rules like these cannot work propperly, as described in https://github.com/symplify/symplify/issues/3175
When this gets solved in PHPStan somehow, we can get into it. 

For now the ideal switch is to use PHPStan rule that warns about missing `@see` reference:
https://github.com/symplify/phpstan-rules/blob/main/docs/rules_overview.md#seeannotationtotestrule

**Comment by TomasVotruba** [comment]
Fixed via https://github.com/rectorphp/rector-phpunit/pull/14/files
