### ISSUE TITLE
Data providers may come from extended classes

### ISSUE THREAD

**Issue by marmichalski** [rectorphp/rector-phpunit#142]
Imagine a Test class, let's call it A, extending some other (potentially) abstract Test class, B, that has defined example dataProvider methods and class A is using data providers from class B.  
This makes [DataProviderClassMethodFinder](https://github.com/rectorphp/rector-phpunit/blob/97cab8de4f7c6cd2b1006e3394409a7c98425bde/src/NodeFinder/DataProviderClassMethodFinder.php#L31) throw exception as the docblock referenced method is not contained in the same class.

The simplest solution would be to change exception throwing into a `continue` step, disadvantage is that the extended class method won't be recognized as a data provider - but this is already happening for the base class that provides the data provider methods only 🙈.

<details>
  <summary>Very basic code sample</summary>

```php

abstract class SomeAbstractTest extends TestCase
{
    public function provideData()
    {
        yield [1];
    }
}

final class SomeTest extends SomeAbstractTest
{
    /**
     * @dataProvider provideData()
     */
    public function test()
    {
    }
}
```
</details>

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/rectorphp/rector-phpunit/pull/143

Thank you :+1:
