### ISSUE TITLE
Do not replace method covers annotations with attributes in CoversAnnotationWithValueToAttributeRector

### ISSUE THREAD

**Issue by jnoordsij** [rectorphp/rector-phpunit#149]
Currently, this class refactors all occurences of cover annotations, as described in the [example](https://github.com/rectorphp/rector-phpunit/blob/main/docs/rector_rules_overview.md#coversannotationwithvaluetoattributerector). However, method-based attributes are not supported and never will be (see https://github.com/sebastianbergmann/phpunit/issues/5175 and https://github.com/sebastianbergmann/phpunit/issues/4502).

Applying this rule to a testsuite that uses method-based annotations will now result into a broken tests suite (`Attribute "PHPUnit\Framework\Attributes\CoversClass" cannot target method (allowed targets: class)`).

I think there are two possible solutions:
- ignore all method-based annotations altogether, possibly with some warning message provided to users to notify them on this behavior
- move all the annotations to be class-based, as using multiple covers attributes on a class is allowed

**Comment by jnoordsij** [comment]
Hey there!

The issue is not Rector failing, but actually Rector producing code that makes PHPUnit fails. This already happens on the documented example in this repository:
```diff
 use PHPUnit\Framework\TestCase;
+use PHPUnit\Framework\Attributes\CoversClass;
+use PHPUnit\Framework\Attributes\CoversFunction;

-/**
- * @covers SomeClass
- */
+#[CoversClass(SomeClass::class)]
 final class SomeTest extends TestCase
 {
-    /**
-     * @covers ::someFunction
-     */
+    #[CoversFunction('someFunction')]
     public function test()
     {
     }
 }
```

should be 

```diff
 use PHPUnit\Framework\TestCase;
+use PHPUnit\Framework\Attributes\CoversClass;
+use PHPUnit\Framework\Attributes\CoversFunction; # OPTIONALLY

-/**
- * @covers SomeClass
- */
+#[CoversClass(SomeClass::class)]
+#[CoversFunction('someFunction')] # OPTIONALLY
 final class SomeTest extends TestCase
 {
-    /**
-     * @covers ::someFunction
-     */
     public function test()
     {
     }
 }
```

(Note: I've attempted to use the demo to run the code, but could not get it to apply this rule, see https://getrector.com/demo/e7acfebb-4fe4-42b0-aa5e-f92ecce676f8).

**Comment by TomasVotruba** [comment]
Seems the opening PHP tag was missing: https://getrector.com/demo/94bd6a93-2b06-4823-8a9a-be9058fad69d

Is that one correct false positive?

**Comment by jnoordsij** [comment]
Ah that explains a lot! I've created https://getrector.com/demo/34c92edd-6a12-46e2-a1d3-fcbb6003a8e0 now, which currently has 2 changes but should have either:
1. no changes at all
2. result in
```diff
 <?php
 
 use PHPUnit\Framework\TestCase;
@@ -4,16 +4,12 @@
 
+#[\PHPUnit\Framework\Attributes\CoversFunction('someFunction')]
+#[\PHPUnit\Framework\Attributes\CoversClass(SomeClass::class)]
 final class SomeTest extends TestCase
 {
-    /**
-     * @covers ::someFunction
-     */
     public function test()
     {
     }
 
-    /**
-     * @covers SomeClass
-     */
     public function another_test()
     {
     }
```

**Comment by TomasVotruba** [comment]
Thanks for the amazing diffs. That made everything easier to understand for me :+1:

**Comment by jnoordsij** [comment]
Thanks for solving this; hopefully will find some time to try this out soon

**Comment by gisostallenberg** [comment]
If I change it this way I get an error:
```
Function "::someFunction" is not a valid target for code coverage
```
Or am I missing something?

**Comment by jnoordsij** [comment]
> If I change it this way I get an error:
> 
> ```
> Function "::someFunction" is not a valid target for code coverage
> ```
> 
> Or am I missing something?

Some things, like class functions combined with `@coversDefaultClass`, are no longer supported: see https://github.com/sebastianbergmann/phpunit/issues/4502. I'm not sure if there some more general way to detect those and handle them differently (i.e. delete them altogether, as they are no longer supported), but the solution implemented to resolve this issue at least moves the code from "not running at all" to "running with warnings" in these cases.

If you have a suggestion for improvement, you might want to create a separate issue for that.
