### ISSUE TITLE
[PHPUnit 10] Add dynamic data provider content to "static" one rules

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-phpunit#157]
Motivation?

* lazyness :)
* https://github.com/symfony/symfony/pull/48668#issuecomment-1420980832

Inspiration:

* https://github.com/symfony/symfony/pull/49244/files#diff-1be27ccb568de8ba9ddeaa8bd720494dd529c3ed21121e4c9d06838eabf7729b
* https://github.com/symfony/symfony/pull/48980/files#diff-14bef5efeb6809c439378585a6768d4b04aa55521ea20527ae20c388157953ca

**Comment by alexandre-daubois** [comment]
This is a bit of a massive one and has yet to be approved, but here is another one in case this could help you! 🙂 

- https://github.com/symfony/symfony/pull/49288

**Comment by TomasVotruba** [comment]
I've been looking into that and this domain looks very ambiguious and not-determenistics. In these cases the PHPStan report + manual fix would be better choice :+1:
