### ISSUE TITLE
`AddDoesNotPerformAssertionToNonAssertingTestRector` incorrectly adds `@doesNotPerformAssertions` annotation

### ISSUE THREAD

**Issue by Wirone** [rectorphp/rector-phpunit#165]
Consider test method and its related methods:

```php
public function testSomething(): void
{
    $this->mockSomething(); // This makes assertion internally by using `MockObject::expects()`
    $this->runSomething(true);
}

private function mockSomething(): void
{
    $this->something // This is mock prepared in setUp()
        ->expects(self::once())
        ->method('handle');
}
```

Currently `AddDoesNotPerformAssertionToNonAssertingTestRector` adds `@doesNotPerformAssertions` annotation to such tests, which is not true. Method itself does not have assertion calls, but other method(s) called within test makes assertions with `MockObject::expects()`.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-phpunit/pull/211
