### ISSUE TITLE
`AssertTrueFalseToSpecificMethodRector` class incorrectly assumes `class-string` is an `object`

### ISSUE THREAD

**Issue by ghostwriter** [rectorphp/rector-phpunit#198]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | `^0.17.1` |
| Installed as   | `composer`  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/3be3c0d9-dbea-4e1d-8c59-ea7fa84c4440

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoFileTest extends TestCase
{
    /**
     * @var class-string<ExceptionInterface::class> $exception
     * @dataProvider exceptionsDataProvider
     **/
    public function testExceptionIsInstanceOfExceptionInterface(string $exception): void
    {
        self::assertTrue(is_a($exception, ExceptionInterface::class, true));
    }
    
    public static function exceptionsDataProvider(): iterable
    {
        yield from [
            ExceptionInterface::class => [ExceptionInterface::class]
        ];
    }
}

interface ExceptionInterface {
}
```

### Responsible rules

* `AssertTrueFalseToSpecificMethodRector`

## Expected Behavior

to remain unchanged.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by ghostwriter** [comment]
@TomasVotruba thanks for looking into this.

Here is the isolated failing demo link you requested. https://getrector.com/demo/3be3c0d9-dbea-4e1d-8c59-ea7fa84c4440

**Comment by samsonasik** [comment]
@ghostwriter you can click "Create a Test" button next to create fixture file for failing test case, would be better if you can provide a patch as well ;)

**Comment by ghostwriter** [comment]
Sure, I'll send a PR with a fix.
