### ISSUE TITLE
Rector run Failed `TryCatchToExpectExceptionRector`

### ISSUE THREAD

**Issue by ghostwriter** [rectorphp/rector-phpunit#199]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | `^0.17.1` |
| Installed as   | `composer`  |

> System error: \"array_merge(): Argument rectorphp/rector#2 must be of type array, null given on line 104.

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/75a8fde7-5d55-4b3c-84a2-3df83076349c

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoFileTest extends TestCase
{
    public function testThrowsBadMethodCallException(): void
    {
        try {
            throw new BadMethodCallException();
        } catch (BadMethodCallException $badMethodCallException) {
            self::assertSame($badMethodCallException::class, BadMethodCallException::class);
            return;
        }

        self::fail('Exception was not thrown');
    }
}

class BadMethodCallException extends \RuntimeException {
}
```

### Responsible rules

* `TryCatchToExpectExceptionRector`

## Expected Behavior

to run and remain unchanged.

**Comment by TomasVotruba** [comment]
Sure :+1:

**Comment by ghostwriter** [comment]
Thanks, I'll send a PR with a fix.
