### ISSUE TITLE
Referencing a class name in an exception message breaks refactoring to expectExceptionMessage

### ISSUE THREAD

**Issue by camporter** [rectorphp/rector-phpunit#26]
`\Rector\PHPUnit\PhpDoc\PhpDocValueToNodeMapper::mapGenericTagValueNode` is used for both the expected exception and the expected exception message when refactoring php doc tags into exception methods, which opportunistically tries to use class constants.

If there happens to be `::` in the exception message, then the exception message isn't treated as a string. Would it be possible to handle exception messages (and maybe regexps) as strings always? Otherwise invalid class constants can be written and generate invalid PHP.

**Comment by camporter** [comment]
@samsonasik Created #28 , thanks

**Comment by samsonasik** [comment]
fixed at https://github.com/rectorphp/rector-phpunit/pull/29. I am closing it.
