### ISSUE TITLE
AssertEqualsToSameRector doesn't consider nullable scalars

### ISSUE THREAD

**Issue by KenWeich** [rectorphp/rector-phpunit#261]
Consider having a property that is typed as follows:

```php
private ?string $myProperty;
```

Now using this property as the expected value in an `assertEquals` and running `AssertEqualsToSameRector` rule over it, will not change it to `assertSame` even though it would be desired.

Is there any other rule that takes care of that or is that just something that wasn't considered yet?

**Comment by KenWeich** [comment]
Yes and yes

**Comment by stefantalen** [comment]
That is strange, because then the demo link should show changes.

Since it doesn't, I think something else changes it.

What rules does Rector show it applies?

**Comment by KenWeich** [comment]
Sorry for the late answer...
Yeah, the demo link itself doesn't work, but then I realized that the demo uses `TestCase` without importing it. So adding `use PHPUnit\Framework\TestCase;` fixed it. Rector then applied the AssertEqualsToSameRector Rule.

**Comment by samsonasik** [comment]
@KenWeich that mean it close-able?

**Comment by KenWeich** [comment]
@samsonasik Yeah. 
I would still be interested though when and how it was fixed if that's even traceable. Do you have any info on that?

**Comment by samsonasik** [comment]
I think you can use git blame to check it :)
