### ISSUE TITLE
Add a blank line after trait for addprophecytraitrector rule

### ISSUE THREAD

**Issue by eerison** [rectorphp/rector-phpunit#279]
is there any way to add a blank like between trait and method?

this rule https://github.com/rectorphp/rector-phpunit/blob/main/docs/rector_rules_overview.md#addprophecytraitrector

Should apply

```diff
+    use ProphecyTrait;
+
```

But it is not adding this blank line after trait.

Should it be handled here or other tool should do it like phpcs?

**Comment by samsonasik** [comment]
There is NewlineAfterStatementRector rule for that 

https://github.com/rectorphp/rector-src/blob/main/build/target-repository/docs/rector_rules_overview.md#newlineafterstatementrector

You may need to run twice when apply `NewlineAfterStatementRector` to ensure everything printed corectly.

**Comment by samsonasik** [comment]
Oh, it seems that's not cover use trait, in that case, you need to have `new Nop()` after that, ensure that uses only once.

**Comment by samsonasik** [comment]
In case `NewlineAfterStatementRector` don't apply on use trait, the feature should be on `NewlineAfterStatementRector`
