### ISSUE TITLE
Move DataProviderArrayItemsNewlinedRector to rector-phpunit

### ISSUE THREAD

**Issue by eerison** [rectorphp/rector-phpunit#287]
Shouldn't this rule [DataProviderArrayItemsNewlinedRector](https://github.com/rectorphp/rector/blob/main/rules/CodingStyle/Rector/ClassMethod/DataProviderArrayItemsNewlinedRector.php) be placed in this repository instead of main repository?

in theory yes https://github.com/rectorphp/rector/blob/main/rules/CodingStyle/Rector/ClassMethod/DataProviderArrayItemsNewlinedRector.php#L96

😄

**Comment by TomasVotruba** [comment]
That would be better location indeed :)
