### ISSUE TITLE
AnnotationWithValueToAttributeRector not applied due to DoctrineAnnotationTagValueNode

### ISSUE THREAD

**Issue by mfn** [rectorphp/rector-phpunit#297]
Hi,

I noticed some `@group …` directives not being adapted and after a bit debugging I notice that in `\Rector\PHPUnit\AnnotationsToAttributes\Rector\Class_\AnnotationWithValueToAttributeRector::refactor` the call to `getTagsByName` returned `DoctrineAnnotationTagValueNode` instead of `GenericTagValueNode`.

But there is this check which makes it not pass:
```php
if (!$desiredTagValueNode->value instanceof GenericTagValueNode) {
    continue;
}
```

As to why: well, I've a (namespaces) class `\Project\Models\Group` imported in some tests and I guess rector treats the class `Group` special with `@group`. However, in my case there's no relation here and since the default config in `annotations-to-attributes.php` uses the FQCN anyway, there's no clash.

What can I do to still have such `@group` being converted?

I'm talking about using this in CI, so I'm not looking for a one-time transformation here.

Thanks

**Comment by TomasVotruba** [comment]
Hi, thanks for patience on this one.
I'll make it a priority to pass.

Could you share a broken test fixture using demo?
https://getrector.com/demo

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:

**Comment by daveharding** [comment]
Hi - we are also having this issue when trying to convert Symfony's Serialization group annotations to attributes.

I'm seeing the same issue described by @mfn - in that the class DoctrineAnnotationTagValueNode does not pass these tests:

`if (!$docNode instanceof PhpDocTagNode) {}`

`if (!$docNode->value instanceof GenericTagValueNode) {}`

I've set up a demo here, please let me know if it needs any more info - https://getrector.com/demo/bb8e05f8-461c-4ed0-8f4c-637d880e508a

I'm pretty sure it has something to do with the fact that we have a "Groups" class, `App\Entity\Groups` which shares the classname, albeit in a separate namespace.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

Could you open a new PR with flailing test fixture? That way it would be easier to fix it for us

**Comment by samsonasik** [comment]
@daveharding I tested it at PR fixture:

- https://github.com/rectorphp/rector-src/pull/6625

it seems working ok on target `Symfony\Component\Serializer\Attribute\Groups` class, while skip current sub namespace as not defined in the configured rule.

**Comment by daveharding** [comment]
Thanks for getting back to me @TomasVotruba, and for the test PR @samsonasik .

I'm having an issue adding a test fixture as per https://getrector.com/documentation/reporting-issue-with-rector

This fails during composer install, then subsequently `composer phpstan` also fails to run, details below.

`  - Applying patches for illuminate/container
    https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/illuminate-container-container-php.patch (0)
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d '/Users/davidharding/Developer/Cinolla/_Packages/RectorGroupsFix/vendor/illuminate/container' < '/var/folders/jn/xpf0g3jx4vl_y4y8m0_7glwr0000gn/T/67696436b5aa3.patch'" exceeded the timeout of 300 seconds.

In Patches.php line 331:
                                                                                                                      
  Cannot apply patch 0 (https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/illuminate-container  
  -container-php.patch)! `


PHPStan error:

`In Resolver.php line 115:
                                                                                         
  Service 'rules.226': Class 'Symplify\PHPStanRules\Rules\NoDynamicNameRule' not found.`


I've done some more digging into this, and it seems that:

https://github.com/rectorphp/rector-src/blob/22915933d05f2a3e38355cd150ec67401a0fe3b9/src/BetterPhpDocParser/PhpDoc/DoctrineAnnotationTagValueNode.php#L65

This line is returning our Doctrine Entity class "App\Entity\Groups" as the $resolvedClass, when it should be returning "Symfony\Component\Serializer\Annotation\Groups"

Happy to create a test fixture once I can get it running. Using `PHP 8.2.26`
