### ISSUE TITLE
CodeCoverageIgnore attribute is deprecated and should not be used

### ISSUE THREAD

**Issue by martinssipenko** [rectorphp/rector-phpunit#303]
As described in https://github.com/sebastianbergmann/phpunit/issues/5235 and https://github.com/sebastianbergmann/phpunit/issues/5513 the `CodeCoverageIgnore` attribute was a mistake and is now deprecated, therefore Rector should not try to replace annotation with the attribute.

https://github.com/rectorphp/rector-phpunit/blob/2095737213ec328db197774a5d073e962c14174c/config/sets/annotations-to-attributes.php#L91

**Comment by samsonasik** [comment]
@martinssipenko Could you create a PR to fix it? Thank you.

**Comment by martinssipenko** [comment]
@samsonasik created https://github.com/rectorphp/rector-phpunit/pull/304
