### ISSUE TITLE
WithConsecutiveRector is not working as expected

### ISSUE THREAD

**Issue by nicolashohm** [rectorphp/rector-phpunit#327]
I saw `WithConsecutiveRector` added in #246 to the PHPUnit 10 rule set, and was keen to use it. But unfortunately, it's not working. 

I took the example from `tests/Rector/StmtsAwareInterface/WithConsecutiveRector/Fixture/some_class.php.inc` and defined PersonService like this:
```php
class PersonService {
    public function prepare($value1, $value2) {}
}
```

Original test:
```php
        $mock = $this->createMock(PersonService::class);
        $mock->expects($this->exactly(2))
            ->method('prepare')
            ->withConsecutive(
                [1, 2],
                [3, 4],
            );

        $mock->prepare(9, 9);
        $mock->prepare(9, 9);
```
=> Test fails as expected with:
```
Parameter 0 for invocation #0 PersonService::prepare(9, 9) does not match expected value.
Failed asserting that 9 matches expected 1.
```

after running the `WithConsecutiveRector`:
```php
        $mock = $this->createMock(PersonService::class);
        $matcher = $this->exactly(2);
        $mock->expects($matcher)
            ->method('prepare')->willReturnCallback(static fn(): array => match ($matcher->numberOfInvocations()) {
            1 => [1, 2],
            2 => [3, 4],
        });

        $mock->prepare(9, 9);
        $mock->prepare(9, 9);
```
=> Test is successful even though it shouldn't cause 9 is not equals to the expected value.

the result I get from the rector is already different from what's in the documentation. So I also checked if it would work with the result the documentation provides:
```php
        $mock = $this->createMock(PersonService::class);
        $matcher = $this->exactly(2);
        $mock->expects($matcher)
            ->method('prepare')->willReturnCallback(function () use ($matcher) {
                return match ($matcher->numberOfInvocations()) {
                    1 => [1, 2],
                    2 => [3, 4],
                };
            });

        $mock->prepare(9, 9);
        $mock->prepare(9, 9);
```
=> Test is successful again, even though it still shouldn't.

Let me know if I missed something. Otherwise, I've unfortunately no idea how to fix this rector.

**Comment by samsonasik** [comment]
@f-albert reimplement at https://github.com/rectorphp/rector-phpunit/pull/313, could you check?

**Comment by TomasVotruba** [comment]
Closing as outdated and lack of feedback last 4 months. Thanks for understanding :+1: 

This rule is quite a challange :) if you come across a weird case, please submit a test fixture here: 

https://github.com/rectorphp/rector-phpunit/tree/bffd16339732095ba84bf21475eac749c1c9a154/rules-tests/PHPUnit100/Rector/StmtsAwareInterface/WithConsecutiveRector/Fixture
