### ISSUE TITLE
Set `PHPUNIT_100` and `AssertIssetToSpecificMethodRector::refactorPropertyFetchNode()` should be mutually exclusive

### ISSUE THREAD

**Issue by phansys** [rectorphp/rector-phpunit#336]
Assertions that operate on class/object properties were [removed](https://github.com/sebastianbergmann/phpunit/issues/4601) in PHPUnit 10.

https://github.com/rectorphp/rector-phpunit/blob/e23a9b57b934e2ecc1c0ef37dab3a980ec11d4d3/rules/CodeQuality/Rector/MethodCall/AssertIssetToSpecificMethodRector.php#L108

**Comment by TomasVotruba** [comment]
Indeed, thanks for reporting. We'll should move this rule into version-based itself. The method names in PHPUnit are changing too often :)
