### ISSUE TITLE
NamedArgumentForDataProviderRector not working because the class DataProvider is using a scoped rector version

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector-phpunit#344]
Hello there,

I've just tried the [new `NamedArgumentForDataProviderRector` rule](https://github.com/rectorphp/rector-phpunit/pull/330) and was surprised that it changed nothing in my project. I started debugging and the issue was this : 

```diff
-use RectorPrefix202406\PHPUnit\Framework\Attributes\DataProvider;
+use PHPUnit\Framework\Attributes\DataProvider;
```

I'm not sure if the issue is that the DataProvider class must be referenced somewhere in Rector's code to be properly handled when scoped, or if the issue is with how Rector is installed in our project (which is quite standard I think, but these things tend to get complicated real fast, so who knows...).

gnutix

**Comment by TomasVotruba** [comment]
Hi, indeed, this class name should be untouched.

@samsonasik Could you fix this one, as it requires a bit of Rector internals?

**Comment by samsonasik** [comment]
Yes, here the PR:

- https://github.com/rectorphp/rector-phpunit/pull/347
