### ISSUE TITLE
NamedArgumentForDataProviderRector changes data providers that it doesn't need to

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector-phpunit#346]
Hey ya,

Let me know if I'm wrong, but I think this kind of change is unnecessary (I tried reverting the change and PHPUnit does not report any deprecation) : 

![image](https://github.com/rectorphp/rector-phpunit/assets/310134/35166619-e4cd-465c-a848-60d55b17e25d)

While this one is probably necessary, as there cannot be un-named arguments after named arguments (yet PHPUnit does not report the deprecation either... probably a miss on their side) : 

![image](https://github.com/rectorphp/rector-phpunit/assets/310134/e729f0e8-2962-4d0b-8e4c-f19d2b7da024)

It doesn't really hurt though, so I get it if you don't want to fix it. But it might generate quite of lot of useless diff for some projects, which could be avoided.

gnutix

**Comment by TomasVotruba** [comment]
Hey, I agree. There should not be changed.
Could you send PR with fix and test?

**Comment by gnutix** [comment]
Sorry, too much on my plate these days.

**Comment by TomasVotruba** [comment]
No worries. The rule works as intended, it's just an optional way to use a feature: https://github.com/sebastianbergmann/phpunit/pull/5225

I'll remove the rule from main set, so it's not enforcing an optional feature.
