### ISSUE TITLE
PreferPHPUnitThisCallRector vs. PHPStan Strict Rules

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector-phpunit#413]
when enabling `PHPUnitSetList::PHPUNIT_CODE_QUALITY` in a PHPUnit 10.x based projects I get a lot of 

`self::assertSame($expected, $result);` lines turned into `$this->assertSame($expected, $result);`
(every changed occurence turns into a PHPStan strict error)

even on [PHPUnit 11.x the asserts methods are static](https://github.com/sebastianbergmann/phpunit/blob/7296d39d802b488d5dd6d33eb9f94cfde5dd4bb1/src/Framework/Assert.php#L1709).

I wonder why this PreferPHPUnitThisCallRector  exists and whether its really a good idea to have it in `PHPUnitSetList::PHPUNIT_CODE_QUALITY`...?

IMO doing the opposite would be more useful (turn `$this` into `static`) - but at least removing this rule from `PHPUnitSetList::PHPUNIT_CODE_QUALITY` would be a good first thing IMO.

wdyt?

**Comment by TomasVotruba** [comment]
Using `$this` in PHPUnit cases make more sense, as it's tests are classes. Classes that use parent method locally. `static` is there to allow edge-case functional testing.

In case of Pest this would make more sense, as those tests are functions-first.

If you prefer something else, register this rule with different your preffered configuration :+1:
