### ISSUE TITLE
Add option to replace TestClassNameResolver with custom implementation

### ISSUE THREAD

**Issue by dorrogeray** [rectorphp/rector-phpunit#51]
Hi, we have our directory structure in our project like this:

- src
- tests
  - E2E
  - Functional
  - Unit

So for class `App\Services\SomeService` we have test with FQCN `App\Tests\Unit\Services\SomeService`, the `Unit` being what breaks the default `TestClassNameResolver` implementation.

Do you think it would be a good idea to allow the `TestClassNameResolver` to be replaced via configuration by custom implementation, or perhaps by a callback, or should we try to find a different solution?

Thanks!

**Comment by TomasVotruba** [comment]
Hi, this can done via Symfony DI mechanism, in case there is an interface to autowire.

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-phpunit/pull/52
