### ISSUE TITLE
[PHPUnit 10] Add rule for migrate annotation to attribute

### ISSUE THREAD

**Issue by lyrixx** [rectorphp/rector-phpunit#69]
ref: https://github.com/sebastianbergmann/phpunit/issues/4502

**Comment by TomasVotruba** [comment]
That looks like a lot of work. We're now focusing on improving Rector core to make ruls behavior more transparent.
Would you like to contribute this one?

**Comment by lyrixx** [comment]
I don't have the bandwidth 😬 I'm sorry. I opened the issue to give some visibility to this new feature of PHPUnit

**Comment by TomasVotruba** [comment]
I see. We use issue to handle mostly bugs or PHP upgrade paths. Tools mostly depends on community activity, so it reflects the real demand for upgrade. 

E.g. I have used maybe 1-2 annotations from thta whole list. Let's wait for the first contributor :)

**Comment by TomasVotruba** [comment]
Mostly handled now, let us know if you find a missing case!
