### ISSUE TITLE
GetMockBuilderGetMockToCreateMockRector breaks test code

### ISSUE THREAD

**Issue by kenjis** [rectorphp/rector-phpunit#86]
```diff
1) tests/system/Email/EmailTest.php:138

    ---------- begin diff ----------
@@ @@

     public function testDestructDoesNotThrowException()
     {
-        $email = $this->getMockBuilder(Email::class)
-            ->disableOriginalConstructor()
-            ->onlyMethods(['sendCommand'])
-            ->getMock();
+        $email = $this->createMock(Email::class);
         $email->method('sendCommand')
             ->willThrowException(new ErrorException('SMTP Error.'));
    ----------- end diff -----------

Applied rules:
 * GetMockBuilderGetMockToCreateMockRector (https://github.com/lmc-eu/steward/pull/187/files#diff-c7e8c65e59b8b4ff8b54325814d4ba55L80)
```

But when I run the test, I got the error:
```console
$ vendor/bin/phpunit tests/system/Email/EmailTest.php
PHPUnit 9.5.21 #StandWithUkraine

Runtime:       PHP 8.0.20
Configuration: .../CodeIgniter4/phpunit.xml

........E                                                           9 / 9 (100%)E                                                           9 / 9 (100%)

Time: 00:00.358, Memory: 14.00 MB

There was 1 error:

1) CodeIgniter\Email\EmailTest::testDestructDoesNotThrowException
PHPUnit\Framework\MockObject\MethodNameNotConfiguredException: Method name is not configured

ERRORS!
Tests: 9, Assertions: 20, Errors: 1.
```

**Comment by samsonasik** [comment]
it seems there is test that remove `onlyMethods` for it:

https://github.com/rectorphp/rector-phpunit/blob/3f4cc815bb7cd8c5502cd873139c4cfc2734bfe5/tests/Rector/MethodCall/GetMockBuilderGetMockToCreateMockRector/Fixture/only_methods.php.inc#L11

and it registered at:

https://github.com/rectorphp/rector-phpunit/blob/3f4cc815bb7cd8c5502cd873139c4cfc2734bfe5/src/Rector/MethodCall/GetMockBuilderGetMockToCreateMockRector.php#L25

@kenjis is the error happen when `->method('sendCommand')` is called?

**Comment by kenjis** [comment]
Yes, I think so.

**Comment by TomasVotruba** [comment]
Let's continue discussion in one place to keep it simple: https://github.com/rectorphp/rector-phpunit/pull/87#issuecomment-1167574087

**Comment by SantosSi** [comment]
Find a comment that could explain the misbehavior [in my comment in #87](https://github.com/rectorphp/rector-phpunit/pull/87#issuecomment-1221326304).

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-phpunit/pull/205
